# Generated by Django 3.1.7 on 2021-05-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(),
        ),
    ]
